dist: xenial
language: python
branches:
  only:
    - master
python: 3.6
virtualenv:
  system_site_packages: true
# command to install dependencies
install:
  - pip install --user -r requirements.txt
  - pip install .
# command to run tests
script: pytest